using Printf, CSV, Random

# Write a network to the .nnet format used by NeuralVerification.jl.
# h: layer sizes [h_0, h_1, ..., h_n]
# W: weight matrices per layer
# b: bias vectors per layer
function write_nnet_full(filename::String, h::Vector{Int}, W::Vector{Matrix{Float64}}, b::Vector{Vector{Float64}})
    n_layers = length(h) - 1

    open(filename, "w") do io
        println(io, "// .nnet file generated by Julia")
        println(io, join(n_layers, ", "))
        println(io, join(h, ", "))

        # Normalization placeholders (no normalization applied)
        for _ in 1:5
            println(io, join(0, ", "))
        end

        # Weights and biases, layer by layer
        for i in 1:n_layers
            for row in 1:size(W[i], 1)
                println(io, join(map(x -> @sprintf("%.16f", x), W[i][row, :]), ", "))
            end
            for val in map(x -> @sprintf("%.16f", x), b[i])
                println(io, val)
            end
        end
    end
end

# Extract layer sizes, weights, and biases from a NeuralVerification.jl network.
function extract_network_data(nnet)
    layers = nnet.layers

    h = Int[size(layers[1].weights, 2)]  # input size
    for layer in layers
        push!(h, size(layer.weights, 1))
    end

    W = [layer.weights for layer in layers]
    b = [layer.bias    for layer in layers]

    return h, W, b, h[1], h[end], length(layers), sum(h)
end

# Generate a random fully-connected ReLU network with given architecture.
# Weights and biases are drawn uniformly from [-1, 1].
# Returns (W, b, N, mean_vals, range_vals) where N = total neuron count.
function generate_nn(h_0, h_n, n, h, nnet_name; network_weights_bound_rng_ind=1)
    rng = Random.seed!(network_weights_bound_rng_ind)

    @assert length(h) == n + 1
    N = sum(h)

    W = [rand(rng, h[i], h[i-1]) .* 2 .- 1 for i in 2:(n+1)]
    b = [rand(rng, h[i])         .* 2 .- 1 for i in 2:(n+1)]

    # No normalization
    mean_vals  = zeros(h_0 + 1)
    range_vals = ones(h_0 + 1)

    return W, b, N, mean_vals, range_vals
end